Import("env")

env.Append(
    SDK_HEADERS=[
        File("overlork_rules.h"),
    ],
    LINT_SOURCES=[
        Dir("."),
    ],
)

libenv = env.Clone(FW_LIB_NAME="overlork_rules")
libenv.ApplyLibFlags()

sources = libenv.GlobRecursive("*.c")

lib = libenv.StaticLibrary("${FW_LIB_NAME}", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
